- hosts: all
  pre_tasks:
  - include_vars: '{{ item }}'
    name: Include playbook configuration.
    tags: [always]
    with_fileglob: ['{{ playbook_dir }}/config.yml']
  roles:
  - {role: elliotweiser.osx-command-line-tools}
  - role: geerlingguy.mac.homebrew
    tags: [homebrew]
  - role: geerlingguy.dotfiles
    tags: [dotfiles]
    when: configure_dotfiles
  - role: geerlingguy.mac.mas
    tags: [mas]
    when: mas_installed_apps or mas_installed_app_ids
  
  tasks:
  - import_tasks: tasks/dock.yml
    tags: [dock]
    when: configure_dock
  - import_tasks: tasks/omz-autosuggest.yaml
    tags: [autoomz]
  - import_tasks: tasks/sudoers.yml
    tags: [sudoers]
    when: configure_sudoers
  - import_tasks: tasks/terminal.yml
    tags: [terminal]
    when: configure_terminal
  - import_tasks: tasks/osx.yml
    tags: [osx]
    when: configure_osx
  - import_tasks: tasks/extra-packages.yml
    tags: [extra-packages]
  - block:
    - include_tasks: '{{ outer_item }}'
      loop_control: {loop_var: outer_item}
      name: Run configured post-provision ansible task files.
      with_fileglob: '{{ post_provision_tasks|default(omit) }}'
    tags: [post]
  vars_files: [default.config.yml]
